"""
==========================================
SULTAN QUANT OS
Report Engine
Version : 2.2
==========================================
"""

from datetime import datetime


# =====================================================
# REPORT ENGINE
# =====================================================

def generate_report(stats: dict) -> str:
    """
    Generate Backtest Report.

    Parameters
    ----------
    stats : dict
        Statistics generated by statistics_engine.

    Returns
    -------
    str
        Formatted report text.
    """

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    report = f"""
============================================================
                    SULTAN QUANT OS
                    BACKTEST REPORT
============================================================

Generated Time
--------------
{now}

============================================================
TRADE STATISTICS
============================================================

Total Trade       : {stats.get("total_trade", 0)}
Winner            : {stats.get("winner", 0)}
Loser             : {stats.get("loser", 0)}
Win Rate          : {stats.get("win_rate", 0):.2f} %

============================================================
PROFIT STATISTICS
============================================================

Gross Profit      : {stats.get("gross_profit", 0):.2f}
Gross Loss        : {stats.get("gross_loss", 0):.2f}
Net Profit        : {stats.get("net_profit", 0):.2f}
Profit Factor     : {stats.get("profit_factor", 0):.2f}

============================================================
TRADE QUALITY
============================================================

Average Win       : {stats.get("average_win", 0):.2f}
Average Loss      : {stats.get("average_loss", 0):.2f}
Average Trade     : {stats.get("average_trade", 0):.2f}
Expectancy        : {stats.get("expectancy", 0):.2f}
Average RR        : {stats.get("average_rr", 0):.2f}

============================================================
RISK STATISTICS
============================================================

Max Win           : {stats.get("max_win", 0):.2f}
Max Loss          : {stats.get("max_loss", 0):.2f}
Max Drawdown      : {stats.get("max_drawdown", 0):.2f}
Drawdown (%)      : {stats.get("max_drawdown_percent", 0):.2f}

============================================================
CONSISTENCY
============================================================

Max Win Streak    : {stats.get("max_win_streak", 0)}
Max Loss Streak   : {stats.get("max_loss_streak", 0)}
Recovery Factor   : {stats.get("recovery_factor", 0):.2f}
Sharpe Ratio      : {stats.get("sharpe_ratio", 0):.2f}

============================================================
END OF REPORT
============================================================
"""

    return report.strip()