"""
==========================================
SULTAN QUANT OS
Report Engine
Version : 4.6.0
==========================================

Responsibilities:

- Generate text report
- Generate HTML report
- Generate visual analytics
- Generate trade journal
- Central report orchestration

Legacy:
- generate_report() preserved

"""

from datetime import datetime
from pathlib import Path


from reports.html_report import (
    generate_html_report
)


from engine.visual_engine import (
    generate_visual_reports
)


from engine.trade_logger import (
    save_trade_journal
)



# =====================================================
# CONFIG
# =====================================================

OUTPUT_DIR = Path(
    "reports/output"
)



TEXT_REPORT_FILE = (

    OUTPUT_DIR /

    "backtest_report.txt"

)



# =====================================================
# LEGACY TEXT REPORT
# =====================================================

def generate_report(
    statistics: dict
) -> str:
    """
    Generate backtest report text.

    Legacy function.
    """

    lines = []


    lines.append(
        "=" * 50
    )

    lines.append(
        "SULTAN QUANT OS BACKTEST REPORT"
    )

    lines.append(
        "=" * 50
    )


    lines.append(

        f"Generated : {datetime.now():%Y-%m-%d %H:%M:%S}"

    )


    lines.append("")



    for key, value in statistics.items():


        if key in [

            "equity_curve",

            "drawdown_curve"

        ]:

            continue



        if isinstance(value, float):

            value = round(

                value,

                2

            )



        lines.append(

            f"{key:20}: {value}"

        )



    lines.append("")



    lines.append(

        "=" * 50

    )



    lines.append(

        "Generated by Sultan Quant OS"

    )


    lines.append(

        "=" * 50

    )



    return "\n".join(
        lines
    )



# =====================================================
# SAVE TEXT REPORT
# =====================================================

def save_text_report(
    statistics: dict,
    filename=None,
):


    OUTPUT_DIR.mkdir(

        parents=True,

        exist_ok=True

    )


    report = generate_report(
        statistics
    )



    if filename:


        output = Path(
            filename
        )


    else:


        output = TEXT_REPORT_FILE



    output.write_text(

        report,

        encoding="utf-8"

    )


    return output

    # =====================================================
# COMPLETE REPORT PIPELINE
# =====================================================

def generate_all_reports(
    statistics: dict,
    trades,
    wfo_analysis: dict = None,
    monte_carlo_analysis: dict = None,
    risk_dashboard: dict = None,
):
    """
    Central report orchestrator.

    Generate:

    - TXT report
    - HTML report
    - Visual analytics
    - Trade journal

    """


    OUTPUT_DIR.mkdir(

        parents=True,

        exist_ok=True

    )



    results = {}



    # ---------------------------------------------
    # TEXT REPORT
    # ---------------------------------------------

    text_report = save_text_report(

        statistics

    )


    results["text_report"] = (

        text_report

    )



    # ---------------------------------------------
    # HTML REPORT
    # ---------------------------------------------

    html_report = generate_html_report(

        statistics=statistics,

        wfo_analysis=wfo_analysis,

        monte_carlo_analysis=monte_carlo_analysis,

        risk_dashboard=risk_dashboard,

    )


    results["html_report"] = (

        html_report

    )



    # ---------------------------------------------
    # VISUAL ANALYTICS
    # ---------------------------------------------

    visual_reports = generate_visual_reports(

        stats=statistics,

        trades=trades,

    )


    results["visual_reports"] = (

        visual_reports

    )



    # ---------------------------------------------
    # TRADE JOURNAL
    # ---------------------------------------------

    journal = save_trade_journal(

        trades

    )


    results["trade_journal"] = (

        journal

    )



    return results