"""
==========================================
SULTAN QUANT OS
HTML Report Template
Version : 4.5.0
==========================================
"""

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="UTF-8">

<title>SULTAN QUANT REPORT</title>

<style>

body{
    font-family:Arial,Helvetica,sans-serif;
    background:#f4f4f4;
    margin:40px;
}

.container{
    max-width:1200px;
    margin:auto;
    background:white;
    padding:30px;
    border-radius:10px;
    box-shadow:0 0 10px rgba(0,0,0,.1);
}

h1{
    text-align:center;
    color:#222;
    margin-bottom:5px;
}

.subtitle{
    text-align:center;
    color:#777;
    margin-bottom:30px;
}

.section{
    margin-top:35px;
}

.section h2{
    border-bottom:2px solid #dddddd;
    padding-bottom:8px;
    color:#333;
}

.info-table{
    width:100%;
    border-collapse:collapse;
}

.info-table td{
    padding:8px;
}

.cards{

    display:grid;

    grid-template-columns:
        repeat(4,1fr);

    gap:15px;

    margin-top:20px;

}

.card{

    background:#fafafa;

    border:1px solid #dddddd;

    border-radius:8px;

    padding:20px;

    text-align:center;

}

.card-title{

    color:#666;

    font-size:14px;

}

.card-value{

    margin-top:10px;

    font-size:26px;

    font-weight:bold;

    color:#222;

}

.chart{

    width:100%;

    margin-top:20px;

    border:1px solid #dddddd;

}

.footer{

    margin-top:40px;

    text-align:center;

    color:#888;

    font-size:12px;

}

</style>

</head>

<body>

<div class="container">

<h1>SULTAN QUANT REPORT</h1>

<div class="subtitle">

Version {{VERSION}}

</div>


<div class="section">

<h2>Backtest Information</h2>

<table class="info-table">

<tr>
<td><b>Strategy</b></td>
<td>{{STRATEGY}}</td>
</tr>

<tr>
<td><b>Symbol</b></td>
<td>{{SYMBOL}}</td>
</tr>

<tr>
<td><b>Timeframe</b></td>
<td>{{TIMEFRAME}}</td>
</tr>

<tr>
<td><b>Generated</b></td>
<td>{{GENERATED}}</td>
</tr>

</table>

</div>


<div class="section">

<h2>Performance Summary</h2>

<div class="cards">


<div class="card">
<div class="card-title">Net Profit</div>
<div class="card-value">{{NET_PROFIT}}</div>
</div>


<div class="card">
<div class="card-title">Win Rate</div>
<div class="card-value">{{WIN_RATE}}</div>
</div>


<div class="card">
<div class="card-title">Profit Factor</div>
<div class="card-value">{{PROFIT_FACTOR}}</div>
</div>


<div class="card">
<div class="card-title">Drawdown</div>
<div class="card-value">{{MAX_DRAWDOWN}}</div>
</div>


<div class="card">
<div class="card-title">Recovery</div>
<div class="card-value">{{RECOVERY}}</div>
</div>


<div class="card">
<div class="card-title">Sharpe</div>
<div class="card-value">{{SHARPE}}</div>
</div>


<div class="card">
<div class="card-title">Winner</div>
<div class="card-value">{{WINNER}}</div>
</div>


<div class="card">
<div class="card-title">Loser</div>
<div class="card-value">{{LOSER}}</div>
</div>


</div>

</div>

<div class="section">

<h2>Equity Curve</h2>

<img
class="chart"
src="equity_curve.png">

</div>


<div class="section">

<h2>Drawdown</h2>

<img
class="chart"
src="drawdown.png">

</div>


<div class="section">

<h2>Profit Distribution</h2>

<img
class="chart"
src="profit_distribution.png">

</div>


<div class="section">

<h2>Monthly Returns</h2>

<img
class="chart"
src="monthly_returns.png">

</div>


<div class="section">

<h2>Walk Forward Optimization</h2>

<div class="cards">


<div class="card">

<div class="card-title">
WFO Score
</div>

<div class="card-value">
{{WFO_SCORE}}
</div>

</div>


<div class="card">

<div class="card-title">
WFO Stability
</div>

<div class="card-value">
{{WFO_STABILITY}}
</div>

</div>


</div>

</div>



<div class="section">

<h2>Monte Carlo Analysis</h2>

<div class="cards">


<div class="card">

<div class="card-title">
Risk Level
</div>

<div class="card-value">
{{MC_RISK}}
</div>

</div>


<div class="card">

<div class="card-title">
Worst Drawdown
</div>

<div class="card-value">
{{MC_DRAWDOWN}}
</div>

</div>


</div>

</div>



<div class="section">

<h2>Strategy Quality Score</h2>


<div class="card">

<div class="card-title">
Final Rating
</div>

<div class="card-value">
{{QUALITY_SCORE}}
</div>

</div>


</div>



<div class="section">

<h2>Trade Journal</h2>

<p>

<a href="trade_journal.csv">

Open Trade Journal (CSV)

</a>

</p>

</div>


<div class="footer">

Generated by SULTAN QUANT OS

</div>


</div>


</body>

</html>
"""