"""
==========================================
SULTAN QUANT OS
Report Engine
Version : 2.5.0
==========================================
"""


from datetime import datetime



def generate_report(
    statistics: dict
) -> str:
    """
    Generate backtest report text.

    Parameters
    ----------
    statistics : dict
        Result from statistics_engine

    Returns
    -------
    str
        Formatted report
    """


    lines = []


    lines.append("=" * 50)
    lines.append("SULTAN QUANT OS BACKTEST REPORT")
    lines.append("=" * 50)

    lines.append(
        f"Generated : {datetime.now():%Y-%m-%d %H:%M:%S}"
    )

    lines.append("")


    for key, value in statistics.items():


        if key in [

            "equity_curve",

            "drawdown_curve"

        ]:

            continue


        if isinstance(value, float):

            value = round(
                value,
                2
            )


        lines.append(
            f"{key:20}: {value}"
        )


    lines.append("")

    lines.append("=" * 50)

    lines.append(
        "Generated by Sultan Quant OS"
    )

    lines.append("=" * 50)


    return "\n".join(lines)